services:
  service1:
    # image: shreyasbalajinagaraja/a1:container1
    build: 
      context: Container_1
    ports:
      - 6000:6000
    volumes:
      - ./:/app/data
    networks:
      - my-network
  service2:
    # image: shreyasbalajinagaraja/a1:container2
    build: 
      context: Container_2
      dockerfile: dockerfile
    ports: 
      - 3300:3300
    volumes:
      - ./:/app/data
    networks:
      - my-network 

volumes:
  my-volume:
    driver: local
    driver_opts:
      type: none
      device: ./
      o: bind
networks:
  my-network: